$mainMod = ALT
$files = thunar
$term = kitty
$browser = flatpak run io.gitlab.librewolf-community #qutebrowser

$scriptsDir = $HOME/.config/hypr/scripts
$configs = $HOME/.config/hypr/configs

$UserConfigs = $HOME/.config/hypr/UserConfigs
$UserScripts = $HOME/.config/hypr/UserScripts
